FROM golang:1.25 AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /rest /app/cmd/rest/main.go


FROM gcr.io/distroless/static-debian12
COPY --from=build /rest /rest
EXPOSE 8080
ENTRYPOINT ["/rest"]